language: android
sudo: false
env:
  - TERM=dumb JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
script:
  - jdk_switcher use oraclejdk8
  - echo sdk.dir $ANDROID_HOME > local.properties
  - ./gradlew --stacktrace assemble
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-27
  - android-28
  - extra-android-m2repository
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_deploy:
  - wget -O - $KEYSTORE_URL | gpg -d --passphrase $KEYSTORE_PASSPHRASE -o keystore.jks
  - >
    ./gradlew assemble
    -Pandroid.injected.signing.store.file=$PWD/keystore.jks
    -Pandroid.injected.signing.store.password=$STORE_PASSWORD
    -Pandroid.injected.signing.key.alias=$KEY_ALIAS
    -Pandroid.injected.signing.key.password=$KEY_PASSWORD
deploy:
  - file_glob: true
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: play-services-core/build/outputs/apk/*/*.apk
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
      tags: false
      condition: $TRAVIS_EVENT_TYPE = api
  - file_glob: true
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: play-services-core/build/outputs/apk/*/*.apk
    skip_cleanup: true
    draft: false
    on:
      tags: true
